#! /bin/sh
bspc rule -r "*"

###---MONITORS---###
laptop_screen=$(xrandr --query | grep 'VGA1')
if [[ $laptop_screen = *connected* ]]; then
	xrandr --output eDP1 --off --output DP1 --off --output HDMI1 --off --output VGA1 --primary --mode 1440x900 --rate 75 --pos 0x0 --rotate normal --output VIRTUAL1 --off
	bspc query -M --names | grep -F -v VGA1 | xargs -r -n1 -I{} bspc monitor {} -r
fi
bspc monitor VGA1 -d I II III IV V

###---AUTOSTART---###
xsetroot -cursor_name left_ptr &
xrdb ~/.Xresources &
picom -b &
feh --bg-fill $HOME/Pictures/wallpapers/wallhaven-eydedl.jpg
~/.config/sxhkd/scripts/touchpad.sh
~/.config/polybar/launch.sh

###---Monitor And Desktop Settings---###
bspc config bottom_padding	0
bspc config left_padding	0
bspc config right_padding	0
bspc config border_width	2
bspc config window_gap		10
bspc config active_border_color '#282828'
bspc config normal_border_color '#282828'
bspc config focused_border_color '#ebdbb2'

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config click_to_focus none

bspc config focus_follows_pointer 	true
bspc config remove_disabled_monitors 	true
bspc config remove_unplugged_monitors 	true
bspc config merge_overlapping_monitors 	true

###---RULES---###
